name: "Release"

# Run on every commit tag which creates a new tag
on:
  workflow_run:
    workflows: ["Pre-release"]
    types:
      - "completed"

# Automatically create a GitHub release when a new tag is pushed to the main branch
jobs:
  release:
    name: "Build Latest"
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Build"
